password = input("What's the password?")
if password == "passwerd":
    relative1 = input("Give me a Relative. ex. brother, sister, aunt, uncle, etc.")
    adjective1 = input("Give me an adjective.")
    adjective2 = input("Give me another adjective.")
    adjective3 = input("One more adjective please!")
    personInRoom1 = input("Give me the name of someone in the room.")
    adjective4 = input("I need another adjective!")
    adjective5 = input("Last adjective!")
    verbED = input("Can I have a verb that ends with ED?")
    bodyPart = input("What about a body part?")
    verbING = input("I need a verb that ends with ING please!")
    pluralNoun = input("Can I have a plural noun?")
    noun = input("Just a regular noun this time!")
    adverb = input("Gimme an adverb.")
    verb1 = input("A verb please!")
    verb2 = input("One more verb!")
    relative2 = input("Can we have another relative please?")
    personInRoom2 = input("The name of someone ELSE in your room!")
    print("Dear "+relative1+",\nI am having a(n) "+adjective1+" time at camp. The counselor is "+adjective2+" and the food is "+adjective3+".\nI met "+personInRoom1+" and we became "+adjective4+" friends. Unfortunately, "+personInRoom1+" is "+adjective5+" and I "+verbED+" my "+bodyPart+" so we couldn't go "+verbING+" like everybody else.\nI need more "+pluralNoun+" and a "+noun+" sharpener, so please "+adverb+" "+verb1+" more when you "+verb2+" back. \nYour "+relative2+", \n"+personInRoom2)
else:
    print("Sorry that's the wrong password")
